spring:
  application:
    name: eureka
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simpledb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimeZone=GMT%2B8
    username: lxc
    password: lxc@123
server:
  port: 7001
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:${server.port}/${spring.application.name}/
  instance:
    hostname: localhost