spring:
  application:
    name: produce
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/simpledb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimeZone=GMT%2B8
    username: lxc
    password: lxc@123
server:
  port: 7002
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka/
  instance:
    hostname: localhost